export enum CodeException {
  IDENTITY_CERTIFICATION_REQUIRED = 'IDENTITY_CERTIFICATION_REQUIRED',
  INVALID_STATUS = 'INVALID_STATUS',
  INACTIVE_USER = 'INACTIVE_USER',
  BANNED_USER = 'BANNED_USER',
  ALREADY_EXIST_EMAIL = 'ALREADY_EXIST_EMAIL',
  ACCESS_TOKEN_REVISION_UNMATCHED = 'ACCESS_TOKEN_REVISION_UNMATCHED',
  NEED_ACCESS_TOKEN = 'NEED_ACCESS_TOKEN',
}
