name: moinda dev CI

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: create env file
        working-directory: ./
        run: |
          cd libs
          cd moinda-pd
          mkdir environment
          cd environment
          touch .env.ci
          cat << EOF >> .env.ci
          ${{ secrets.ENV_FILE }}
      - name: build client files
        working-directory: ./
        run: |
          npm install
          npm run build

      - name: zip file
        run: zip -r moinda-dev.zip ./apps ./libs ./dist ./.eslintrc.js ./.gitignore ./.prettierrc ./nest-cli.json ./package.json ./tsconfig.build.json ./tsconfig.json ./appspec.yml ./scripts

      - name: AWS connect
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./moinda-dev.zip s3://moinda-dev/moinda-dev.zip

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name moinda-dev
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name MOINDA-DEV
          --s3-location bucket=moinda-dev,bundleType=zip,key=moinda-dev.zip
