name: action name

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: create env file
        working-directory: ./
        run: |
          cd libs
          cd moinda-pd
          mkdir environment
          cd environment
          touch .env.ci
          cat << EOF >> .env.ci
          ${{ secrets.ENV_FILE }}
      - name: build client files
        working-directory: ./
        run: |
          npm install
          npm build
#          npm test
          
          
      - name: zip file
        run: zip -r moinda.zip ./apps ./libs ./dist ./.eslintrc.js ./.gitignore ./.prettierrc ./nest-cli.json ./package.json ./tsconfig.build.json ./tsconfig.json ./appspec.yml ./scripts

      - name: AWS connect
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./moinda.zip s3://shitlambda/public/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name moinda
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name moinda
          --s3-location bucket=shitlambda,bundleType=zip,key=public/moinda.zip
